name: "Macropad Configurator"
description: "Configure your LocalBytes Macropad with ease!"
version: "1.0.0"
slug: "macropad-configurator"
init: false

panel_icon: "mdi:dialpad"

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

schema:
  esphome_dir: str

options:
  esphome_dir: "/homeassistant/esphome"

map:
  - homeassistant_config:rw

ingress: true
ingress_port: 3000

homeassistant_api: true
