name: "LocalDeck Configurator"
description: "Configure your LocalBytes LocalDeck with ease!"
slug: "localdeck-configurator"
panel_icon: "mdi:dialpad"

image: ghcr.io/localbytes/hass-localdeck-configurator-{arch}
version: VERSION
arch: [ aarch64, amd64, armhf, armv7, i386 ]
init: false

schema:
  esphome_dir: str

options:
  esphome_dir: "/homeassistant/esphome"

map:
  - homeassistant_config:rw

ingress: true
ingress_port: 3000

homeassistant_api: true
